Text-It/TextItCLI

.idea/misc.xml
src/main/java/com/TextIt/UI/AuthCLI.java
src/main/java/com/TextIt/service/pages/SignUp.java

Adding CLI of login And Sign up page

---

.idea/dataSources.local.xml
.idea/dataSources.xml
.idea/misc.xml
pom.xml

update in pom.xml

---

src/main/java/com/TextIt/UI/AuthCLI.java

changes in static and non statics

---

src/main/java/com/TextIt/UI/AuthCLI.java
src/main/java/com/TextIt/UI/Main.java
src/main/java/com/TextIt/security/OTPHandler.java
src/main/java/com/TextIt/service/pages/SignUp.java

*Last Updated: July 9, 2025*
This pull request upgrades the `TextItCLI` project to **version 1.2**, bringing several critical enhancements for production-readiness. It introduces:
* PostgreSQL database integration for profile and OTP storage
* A robust OTP handling module (`OTPHandler`) with branded email delivery, retry logic, and exception handling
* A complete professional onboarding/signup flow including:
* Email entry
* OTP verification (with retry mechanism)
* Username/password setup
* Phone verification (optional)
* First/last name entry
* Terms & Conditions acceptance
* A T\&C enforcement module with CLI consent prompt
* Significant improvements to exception handling, error messaging, and logging
* JavaDoc enhancements across major classes
* Updated README structure reflecting new …

chore: update README to v1.2 with database, OTP, and signup enhancements

---

pom.xml
src/main/java/com/TextIt/UI/AuthCLI.java
src/main/java/com/TextIt/database/DataBase.java
src/main/java/com/TextIt/service/pages/Login.java
src/main/java/com/TextIt/service/pages/SignUp.java

Insertuser

---

.idea/misc.xml
.idea/sqldialects.xml
src/main/java/com/TextIt/UI/AuthCLI.java
src/main/java/com/TextIt/UI/Main.java
src/main/java/com/TextIt/database/DataBase.java
src/main/java/com/TextIt/model/auth/Authentication.java
src/main/java/com/TextIt/model/utils/CommonMethods.java
src/main/java/com/TextIt/security/Hashing.java
src/main/java/com/TextIt/security/OTPHandler.java
src/main/java/com/TextIt/service/data_structure/linked_list/DoublyLinkedList.java
src/main/java/com/TextIt/service/pages/Feed.java
src/main/java/com/TextIt/service/pages/Login.java
src/main/java/com/TextIt/service/pages/SignUp.java

*Last Updated: July 13, 2025*
This PR introduces the **"Forgot Password"** functionality and major improvements across authentication, database, and utility classes.
The key changes include:
* Adding `handleForgotPassword()` in `Login.java` that lets users reset their password if they type `forgot` at the password prompt.
* Extracting OTP logic into `OTPHandler` class with two new methods:
* `verifyOTPSent()` – Checks if OTP was successfully sent.
* `verifyOTP()` – Validates user-entered OTP.
* Introducing a utility class `CommonMethods` under `model.utils` to store reusable static methods/variables.
* Adding a new method `updateProfile()` in the `Profile` inner class of `DataBase` for updating user fields (password, email, etc.) based on dynamic identifiers.
This enhances usability, …

feat: add forgot password, OTP verification, and profile update support

---

.idea/dataSources.local.xml
.idea/misc.xml
src/main/java/com/TextIt/UI/AuthCLI.java
src/main/java/com/TextIt/database/DataBase.java

database.properties

---

src/main/java/com/TextIt/UI/AuthCLI.java
src/main/java/com/TextIt/service/session/SessionManger.java

ADD UserData and SessionManager Class

---

src/main/java/com/TextIt/database/DataBase.java
src/main/java/com/TextIt/service/pages/Login.java
src/main/java/com/TextIt/service/session/SessionManger.java
src/main/java/com/TextIt/service/user/UserData.java

New Session Feature (On Working Stage )

---

Designs/feed_Design_V1.0.0.txt
src/main/java/com/TextIt/UI/LoginPage.java
src/main/java/com/TextIt/UI/SignupPage.java
src/main/java/com/TextIt/service/pages/LoginAuth.java
src/main/java/com/TextIt/service/pages/SignUpAuth.java

Pagenation

---

src/main/java/com/TextIt/UI/LoginPage.java
src/main/java/com/TextIt/UI/ProfilePage.java
src/main/java/com/TextIt/database/DataBase.java
src/main/java/com/TextIt/service/session/SessionManger.java
src/main/java/com/TextIt/service/user/UserData.java

The "File NOT FOund Bug is fixed."

---

src/main/java/com/TextIt/UI/SearchPage.java
src/main/java/com/TextIt/UI/SettingsPage.java

Setting Layout

---

src/main/java/com/TextIt/UI/AuthCLI.java
src/main/java/com/TextIt/UI/ChatUI.java
src/main/java/com/TextIt/UI/FeedPage.java
src/main/java/com/TextIt/UI/Main.java
src/main/java/com/TextIt/UI/ProfilePage.java
src/main/java/com/TextIt/database/DataBase.java
src/main/java/com/TextIt/service/pages/HomePage.java

Chat modified

---

src/main/java/com/TextIt/UI/SettingsPage.java
src/main/java/com/TextIt/database/DataBase.java

setting page updated but  dynamic is left !!

---

src/main/java/com/TextIt/UI/ChatUI.java
src/main/java/com/TextIt/database/DataBase.java
src/main/java/com/TextIt/service/pages/HomePage.java

Chat Fully completed

---

src/main/java/com/TextIt/UI/AuthCLI.java
src/main/java/com/TextIt/UI/LoginPage.java
src/main/java/com/TextIt/UI/ProfilePage.java
src/main/java/com/TextIt/UI/SearchPage.java
src/main/java/com/TextIt/UI/SignupPage.java
src/main/java/com/TextIt/model/utils/CommonMethods.java
src/main/java/com/TextIt/service/data_structure/Hash_Map/HashMapp.java
src/main/java/com/TextIt/service/pages/HomePage.java

Major changes

---

src/main/java/com/TextIt/UI/FeedPage.java
src/main/java/com/TextIt/UI/ProfilePage.java
src/main/java/com/TextIt/database/DataBase.java

profile page completed

---

src/main/java/com/TextIt/UI/AuthCLI.java

tst commin

---

src/main/java/com/TextIt/service/pages/HomePage.java

Updating the UI of HomePage

---

src/main/java/com/TextIt/UI/CommentPage.java
src/main/java/com/TextIt/UI/FeedPage.java
src/main/java/com/TextIt/model/utils/CommonMethods.java
src/main/java/com/TextIt/service/pages/HomePage.java

done error handaling

---

src/main/java/com/TextIt/UI/ProfilePage.java
src/main/java/com/TextIt/model/utils/CommonMethods.java

Updated profilePage UI

---

src/main/java/com/TextIt/UI/FeedPage.java
src/main/java/com/TextIt/model/utils/CommonMethods.java

done fix in ui border problem

---

src/main/java/com/TextIt/UI/CareerPage.java

Updated Carrer Page UI

---

src/main/java/com/TextIt/UI/SettingsPage.java

Updated UI of setting page

---

src/main/java/com/TextIt/UI/FeedPage.java

Updated UI of FeedPage
